# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Cookie-Jam
version:      0.09
version_from: Jam.pm
installdirs:  site
requires:
    CGI::Uricode:                  0.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
